on:
  push:
    tags:
      - "v*"

jobs:
  deploy-playstore:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Version from Tag
        id: version
        run: |
          TAG_NAME=${{ github.ref_name }}
          VERSION_NAME=${TAG_NAME#v}  # Remove "v" prefix if it exists
          VERSION_CODE=$(echo "$VERSION_NAME" | awk -F. '{print ($1 * 10000) + ($2 * 100) + $3 }')

          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Update pubspec.yaml with Release Version
        run: |
          sed -i "s/^version: .*/version: $VERSION_NAME+$VERSION_CODE/" pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Commit Updated Version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pubspec.yaml
          git commit -m "CI: Set version to $VERSION_NAME+$VERSION_CODE"
          git push origin main

      - name: Decode Keystore from Secret
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Decode Play Store JSON
        run: echo "${{ secrets.PLAYSTORE_JSON }}" > $HOME/playstore-service-account.json

      - name: Build AAB (for Play Store)
        run: flutter build appbundle --release

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: $HOME/playstore-service-account.json
          packageName: com.example.devops_midterm
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
